version: "3.5"

networks:
  inception:

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 443:443
    restart: unless-stopped

volumes:

  mariadb:
    driver: local
    driver_opts:
        device: /home/pweinsto/data/mariadb
        type: none
        o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/pweinsto/data/wordpress
      o: bind